// ─── AUTO-GENERATED BY scripts/generate-enums.js ───
// Do not edit this file directly. Update the C# enums instead.

export const AlcoholCategoryOptions = ['Beer', 'Wine'] as const;
export type AlcoholCategory = typeof AlcoholCategoryOptions[number];

export const BeerColorOptions = ['Dark', 'Amber', 'Pale', 'Brown'] as const;
export type BeerColor = typeof BeerColorOptions[number];

export const BeerStyleOptions = ['Pilsner', 'Helles', 'Dunkel', 'Bock', 'IPA', 'PaleAle', 'Stout', 'Porter', 'Witbier', 'Hefeweizen', 'BerlinerWeisse', 'Gose', 'Lambic', 'Saison', 'BelgianTripel', 'Other'] as const;
export type BeerStyle = typeof BeerStyleOptions[number];

export const BeerStyleFamilyOptions = ['Lager', 'Ale', 'Wheat', 'Sour', 'Belgian', 'Specialty', 'Other'] as const;
export type BeerStyleFamily = typeof BeerStyleFamilyOptions[number];

export const WineAromaOptions = ['Fruity', 'Berry', 'Citrus', 'Floral', 'Spicy', 'Herbal', 'Oak', 'Chocolate', 'Vanilla', 'Other'] as const;
export type WineAroma = typeof WineAromaOptions[number];

export const WineColorOptions = ['Red', 'White', 'Rose', 'Orange', 'Other'] as const;
export type WineColor = typeof WineColorOptions[number];

export const WineStyleOptions = ['Still', 'Sparkling', 'Fortified', 'Dessert', 'Other'] as const;
export type WineStyle = typeof WineStyleOptions[number];

export const WineSweetnessOptions = ['Dry', 'SemiDry', 'SemiSweet', 'Sweet', 'Dessert', 'Other'] as const;
export type WineSweetness = typeof WineSweetnessOptions[number];

