--
-- PostgreSQL database dump
--

\restrict dP161YyApoxH44dEveoHZicELOird5RKh6lFhjTdhON0DbJ2IIofiKVnX8BdBF4

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-06-05 21:08:38

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16885)
-- Name: AlcoholProducts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AlcoholProducts" (
    "ProductId" integer NOT NULL,
    "Name" character varying(255) NOT NULL,
    "Description" character varying(2000) NOT NULL,
    "Abv" numeric(5,2) NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    "CountryOfOrigin" character varying(100) NOT NULL,
    "ImageUrl" text,
    "ImageSourceUrl" text,
    "ImageLocalPath" text
);


ALTER TABLE public."AlcoholProducts" OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16884)
-- Name: AlcoholProducts_ProductId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AlcoholProducts" ALTER COLUMN "ProductId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AlcoholProducts_ProductId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16913)
-- Name: BeerProducts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BeerProducts" (
    "ProductId" integer NOT NULL,
    "Ibu" numeric(5,0) NOT NULL,
    "Srm" numeric(5,0) NOT NULL,
    "Color" integer NOT NULL,
    "Style" integer NOT NULL
);


ALTER TABLE public."BeerProducts" OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16946)
-- Name: Reviews; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Reviews" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "Rating" integer NOT NULL,
    "Comment" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Reviews" OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16945)
-- Name: Reviews_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Reviews" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Reviews_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16968)
-- Name: UserFavorites; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."UserFavorites" (
    "UserId" integer NOT NULL,
    "ProductId" integer NOT NULL
);


ALTER TABLE public."UserFavorites" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16899)
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "UserId" integer NOT NULL,
    "Username" character varying(255) NOT NULL,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Country" character varying(100),
    "TargetAbv" numeric(5,2),
    "AbvTolerance" numeric(5,2),
    "MaxPrice" numeric(18,2),
    "PreferredTagsJson" character varying(2000) NOT NULL,
    "Role" text NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16898)
-- Name: Users_UserId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "UserId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_UserId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16928)
-- Name: WineProducts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."WineProducts" (
    "ProductId" integer NOT NULL,
    "Color" integer NOT NULL,
    "Style" integer NOT NULL,
    "Sweetness" integer NOT NULL,
    "Aromas" integer[] NOT NULL
);


ALTER TABLE public."WineProducts" OWNER TO postgres;

--
-- TOC entry 5048 (class 0 OID 16885)
-- Dependencies: 220
-- Data for Name: AlcoholProducts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AlcoholProducts" ("ProductId", "Name", "Description", "Abv", "Price", "CountryOfOrigin", "ImageUrl", "ImageSourceUrl", "ImageLocalPath") FROM stdin;
11	Pilsner Urquell	Classic Czech pilsner with crisp bitterness.	4.40	3.99	Czech Republic	/product-images/Pilsner-Urquell-11.jpg	https://images.openfoodfacts.org/images/products/859/440/411/0110/front_en.7.400.jpg	C:\\Users\\Ban\\source\\repos\\Titan_Project\\Titan_Project.Server\\wwwroot\\product-images\\Pilsner-Urquell-11.jpg
12	Heineken Original	Well-known Dutch lager with a clean finish.	5.00	3.49	Netherlands	/product-images/Heineken-Original-12.jpg	https://images.openfoodfacts.org/images/products/789/604/550/6590/front_en.3.400.jpg	C:\\Users\\Ban\\source\\repos\\Titan_Project\\Titan_Project.Server\\wwwroot\\product-images\\Heineken-Original-12.jpg
13	Stella Artois	Belgian lager with a balanced malt profile.	5.20	3.89	Belgium	/product-images/Stella-Artois-13.jpg	https://images.openfoodfacts.org/images/products/078/615/000/0052/front_en.19.400.jpg	C:\\Users\\Ban\\source\\repos\\Titan_Project\\Titan_Project.Server\\wwwroot\\product-images\\Stella-Artois-13.jpg
17	Yellow Tail Shiraz	Easy-drinking Australian shiraz with dark fruit.	13.50	9.99	Australia	/product-images/Yellow-Tail-Shiraz-17.jpg	https://images.openfoodfacts.org/images/products/932/221/400/6229/front_en.4.400.jpg	C:\\Users\\Ban\\source\\repos\\Titan_Project\\Titan_Project.Server\\wwwroot\\product-images\\Yellow-Tail-Shiraz-17.jpg
15	Sierra Nevada Pale Ale	American pale ale with bright hop character.	5.60	4.29	United States	/product-images/Sierra-Nevada-Pale-Ale-15.jpg	https://images.openfoodfacts.org/images/products/008/378/337/5251/front_en.3.400.jpg	C:\\Users\\Ban\\source\\repos\\Titan_Project\\Titan_Project.Server\\wwwroot\\product-images\\Sierra-Nevada-Pale-Ale-15.jpg
16	La Marca Prosecco	Fresh sparkling prosecco with orchard fruit notes.	11.00	13.99	Italy	/product-images/La-Marca-Prosecco-16.jpg	https://image.pollinations.ai/prompt/beautiful%20bottle%20of%20La%20Marca%20Prosecco%20Wine%2C%20isolated%20on%20pure%20white%20background%2C%20clean%20studio%20photography%2C%20no%20shadows?width=400&height=600&nologo=true	C:\\Users\\Ban\\source\\repos\\Titan_Project\\Titan_Project.Server\\wwwroot\\product-images\\La-Marca-Prosecco-16.jpg
18	Kim Crawford Sauvignon Blanc	Vibrant New Zealand white with citrus and herb notes.	12.50	15.99	New Zealand	/product-images/Kim-Crawford-Sauvignon-Blanc-18.jpg	https://image.pollinations.ai/prompt/beautiful%20bottle%20of%20Kim%20Crawford%20Sauvignon%20Blanc%20Wine%2C%20isolated%20on%20pure%20white%20background%2C%20clean%20studio%20photography%2C%20no%20shadows?width=400&height=600&nologo=true	C:\\Users\\Ban\\source\\repos\\Titan_Project\\Titan_Project.Server\\wwwroot\\product-images\\Kim-Crawford-Sauvignon-Blanc-18.jpg
19	Taylor Fladgate 10 Year Tawny Port	Aged fortified port with caramel and dried fruit.	20.00	24.99	Portugal	/product-images/Taylor-Fladgate-10.jpg	\N	C:\\Users\\Ban\\source\\repos\\Titan_Project\\Titan_Project.Server\\wwwroot\\product-images\\Taylor-Fladgate-10.jpg
22	Corona Extra	Corona Extra to legendarne meksykańskie piwo jasne typu lager produkowane od 1925 roku przez renomowany browar Grupo Modelo w Meksyku.	4.60	6.50	Mexico	/product-images/Corona-Extra-22.webp	\N	C:\\Users\\Ban\\source\\repos\\Titan_Project\\Titan_Project.Server\\wwwroot\\product-images\\Corona Extra-22.webp
21	Heineken Premium Light	Full taste profile, brewed using all malt to provide a flavoursome foundation. The Cascade hops used impart special floral and citrus notes, along with a light bitterness.	3.20	6.00	Netherlands	/product-images/Heineken-Premium-Light-21.png	\N	C:\\Users\\Ban\\source\\repos\\Titan_Project\\Titan_Project.Server\\wwwroot\\product-images\\Heineken Premium Light-21.png
20	Chateau Ste. Michelle Riesling	Aromatic Washington Riesling with bright acidity.	12.00	12.49	United States	/product-images/Chateau-Ste.-Michelle-Riesling-20.png	\N	C:\\Users\\Ban\\source\\repos\\Titan_Project\\Titan_Project.Server\\wwwroot\\product-images\\Chateau Ste. Michelle Riesling-20.png
23	Tyskie Gronie	A highly crisp and refreshing macro lager with a 5.2% ABV. It features a clean, simple profile blending biscuit malt sweetness with a mild, functional herbal hop bitterness. Subtle fruit esters resembling light apple or banana notes can be detected in the aroma.	5.50	3.00	Poland	/product-images/Tyskie-Gronie-23.webp	\N	C:\\Users\\Ban\\source\\repos\\Titan_Project\\Titan_Project.Server\\wwwroot\\product-images\\Tyskie Gronie-23.webp
14	Guinness Draught	Iconic Irish stout with roasted notes.	4.20	4.49	Ireland	/product-images/Guinness-Draught-14.png	\N	C:\\Users\\Ban\\source\\repos\\Titan_Project\\Titan_Project.Server\\wwwroot\\product-images\\Guinness Draught-14.png
\.


--
-- TOC entry 5051 (class 0 OID 16913)
-- Dependencies: 223
-- Data for Name: BeerProducts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."BeerProducts" ("ProductId", "Ibu", "Srm", "Color", "Style") FROM stdin;
11	40	4	3	1
12	23	3	3	2
13	24	4	2	1
14	45	35	1	7
15	38	6	2	6
21	12	11	3	2
22	18	5	3	1
23	20	3	3	1
\.


--
-- TOC entry 5054 (class 0 OID 16946)
-- Dependencies: 226
-- Data for Name: Reviews; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Reviews" ("Id", "UserId", "ProductId", "Rating", "Comment", "CreatedAt") FROM stdin;
9	1	12	3	Seed review 2	2026-05-23 02:45:06.733243+02
10	1	13	4	Seed review 3	2026-05-23 02:45:06.733408+02
12	1	15	1	Seed review 5	2026-05-23 02:45:06.733573+02
11	1	14	5	Seed review 67	2026-05-23 02:45:06.73349+02
8	1	11	4	Seed review 1	2026-05-23 02:45:06.729503+02
\.


--
-- TOC entry 5055 (class 0 OID 16968)
-- Dependencies: 227
-- Data for Name: UserFavorites; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."UserFavorites" ("UserId", "ProductId") FROM stdin;
1	14
1	13
6	12
6	15
6	21
10	11
10	14
\.


--
-- TOC entry 5050 (class 0 OID 16899)
-- Dependencies: 222
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" ("UserId", "Username", "Email", "PasswordHash", "CreatedAt", "Country", "TargetAbv", "AbvTolerance", "MaxPrice", "PreferredTagsJson", "Role") FROM stdin;
2	user2	user2@local	AQAAAAIAAYagAAAAEJJvBqtCwQa8q3QTq3R7CLUBN8plSJ2UfARlxCEINjS3L0n/RNtQ3VJgq2SD0j067A==	2026-05-22 20:21:41.895828+02	Local	\N	\N	\N	[]	User
3	user3	user3@local	AQAAAAIAAYagAAAAEJ39X1GvxBUI6pqiMU3vOfqXQN8saH/6qaM762A5zD2QQ5PtZnov0gqWk/D5dGgoyw==	2026-05-22 20:21:42.027664+02	Local	\N	\N	\N	[]	User
4	user4	user4@local	AQAAAAIAAYagAAAAEBt7dwMv6PK5qO1C/rMtwgXVKrHmH4lvItfG5cannpwYNq+2rM0EBRDx5Qu4RbYLjg==	2026-05-22 20:21:42.126648+02	Local	\N	\N	\N	[]	User
5	user5	user5@local	AQAAAAIAAYagAAAAEPmz3u+/1YpTKVEEM3a8tlK0nZXndRI7LkcZrUleRQMEhojR2S422lrZFoP33KqydQ==	2026-05-22 20:21:42.211822+02	Local	\N	\N	\N	[]	User
6	admin	admin@local	AQAAAAIAAYagAAAAEHGLCUUcjMXdnhNRtX+Yhfjj+kBrmVptnQ7XhP5q7gIczdoN2IJ6fIMHq3ZWI+1JQw==	2026-05-31 19:40:02.608335+02	\N	\N	\N	\N	[]	Admin
1	user1	user1@local	AQAAAAIAAYagAAAAEPsZfPWS1kET9Wn8o9bplSA/F97rJWQ2+P3FfXLP4qcvttt9MxWpWlHa7USLhi34wA==	2026-05-22 20:21:41.652422+02	Local	\N	\N	\N	[]	User
7	user67	user67@local	AQAAAAIAAYagAAAAEBqZ19ZNeH5O+beQp1WLEF9jzbCebSfujUqWL1Jz/EdHjurLGW43qvV59GWeJK72Og==	2026-06-01 01:16:04.009226+02	United Arab Emirates	\N	\N	\N	[]	User
8	dsfdsfdfs	dsfdsfdfs@local	AQAAAAIAAYagAAAAEG07jl50cZA/50wNasj6esKEK5GNkYbe/aCfsWYmlR2Ueqc3VNNVD/goIBnmOpp5BA==	2026-06-04 19:03:42.222272+02	Andorra	\N	\N	\N	[]	User
9	Test	test@local	AQAAAAIAAYagAAAAEIIFSKtXcsmlu/pmRsg1hkoP9fr2e9yLiILRB0nOa3aQEq2IoXnAIlFHm5XrLw0jLg==	2026-06-05 09:45:48.002642+02	Cuba	\N	\N	\N	[]	User
10	abudaba	abudaba@local	AQAAAAIAAYagAAAAEK84AEflAVZJQvL89DFSeYAdlqD8GtFGuurfraJRiOoABWHucB+GC7lmqjDOZYRmQg==	2026-06-05 12:47:24.545279+02	Niger	5.00	3.50	\N	["Beer","Wine"]	User
\.


--
-- TOC entry 5052 (class 0 OID 16928)
-- Dependencies: 224
-- Data for Name: WineProducts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."WineProducts" ("ProductId", "Color", "Style", "Sweetness", "Aromas") FROM stdin;
16	2	2	1	{}
17	1	1	2	{}
18	2	1	1	{}
19	1	3	4	{}
20	2	4	3	{}
\.


--
-- TOC entry 5061 (class 0 OID 0)
-- Dependencies: 219
-- Name: AlcoholProducts_ProductId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AlcoholProducts_ProductId_seq"', 23, true);


--
-- TOC entry 5062 (class 0 OID 0)
-- Dependencies: 225
-- Name: Reviews_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Reviews_Id_seq"', 20, true);


--
-- TOC entry 5063 (class 0 OID 0)
-- Dependencies: 221
-- Name: Users_UserId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_UserId_seq"', 10, true);


--
-- TOC entry 4879 (class 2606 OID 16897)
-- Name: AlcoholProducts PK_AlcoholProducts; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AlcoholProducts"
    ADD CONSTRAINT "PK_AlcoholProducts" PRIMARY KEY ("ProductId");


--
-- TOC entry 4884 (class 2606 OID 16922)
-- Name: BeerProducts PK_BeerProducts; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BeerProducts"
    ADD CONSTRAINT "PK_BeerProducts" PRIMARY KEY ("ProductId");


--
-- TOC entry 4890 (class 2606 OID 16957)
-- Name: Reviews PK_Reviews; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Reviews"
    ADD CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id");


--
-- TOC entry 4893 (class 2606 OID 16974)
-- Name: UserFavorites PK_UserFavorites; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserFavorites"
    ADD CONSTRAINT "PK_UserFavorites" PRIMARY KEY ("UserId", "ProductId");


--
-- TOC entry 4882 (class 2606 OID 16912)
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("UserId");


--
-- TOC entry 4886 (class 2606 OID 16939)
-- Name: WineProducts PK_WineProducts; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WineProducts"
    ADD CONSTRAINT "PK_WineProducts" PRIMARY KEY ("ProductId");


--
-- TOC entry 4887 (class 1259 OID 16985)
-- Name: IX_Reviews_ProductId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Reviews_ProductId" ON public."Reviews" USING btree ("ProductId");


--
-- TOC entry 4888 (class 1259 OID 16986)
-- Name: IX_Reviews_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Reviews_UserId" ON public."Reviews" USING btree ("UserId");


--
-- TOC entry 4891 (class 1259 OID 16987)
-- Name: IX_UserFavorites_ProductId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_UserFavorites_ProductId" ON public."UserFavorites" USING btree ("ProductId");


--
-- TOC entry 4880 (class 1259 OID 16988)
-- Name: IX_Users_Email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Users_Email" ON public."Users" USING btree ("Email");


--
-- TOC entry 4894 (class 2606 OID 16923)
-- Name: BeerProducts FK_BeerProducts_AlcoholProducts_ProductId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BeerProducts"
    ADD CONSTRAINT "FK_BeerProducts_AlcoholProducts_ProductId" FOREIGN KEY ("ProductId") REFERENCES public."AlcoholProducts"("ProductId") ON DELETE CASCADE;


--
-- TOC entry 4896 (class 2606 OID 16958)
-- Name: Reviews FK_Reviews_AlcoholProducts_ProductId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Reviews"
    ADD CONSTRAINT "FK_Reviews_AlcoholProducts_ProductId" FOREIGN KEY ("ProductId") REFERENCES public."AlcoholProducts"("ProductId") ON DELETE CASCADE;


--
-- TOC entry 4897 (class 2606 OID 16963)
-- Name: Reviews FK_Reviews_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Reviews"
    ADD CONSTRAINT "FK_Reviews_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("UserId") ON DELETE CASCADE;


--
-- TOC entry 4898 (class 2606 OID 16975)
-- Name: UserFavorites FK_UserFavorites_AlcoholProducts_ProductId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserFavorites"
    ADD CONSTRAINT "FK_UserFavorites_AlcoholProducts_ProductId" FOREIGN KEY ("ProductId") REFERENCES public."AlcoholProducts"("ProductId") ON DELETE CASCADE;


--
-- TOC entry 4899 (class 2606 OID 16980)
-- Name: UserFavorites FK_UserFavorites_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserFavorites"
    ADD CONSTRAINT "FK_UserFavorites_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("UserId") ON DELETE CASCADE;


--
-- TOC entry 4895 (class 2606 OID 16940)
-- Name: WineProducts FK_WineProducts_AlcoholProducts_ProductId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WineProducts"
    ADD CONSTRAINT "FK_WineProducts_AlcoholProducts_ProductId" FOREIGN KEY ("ProductId") REFERENCES public."AlcoholProducts"("ProductId") ON DELETE CASCADE;


-- Completed on 2026-06-05 21:08:47

--
-- PostgreSQL database dump complete
--

\unrestrict dP161YyApoxH44dEveoHZicELOird5RKh6lFhjTdhON0DbJ2IIofiKVnX8BdBF4

