import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ENUMS_DIR = path.join(__dirname, '../TitanClassLibrary/Domain/Enums');
const OUTPUT_FILE = path.join(__dirname, '../frontend/src/types/generatedEnums.ts');

function findCsFiles(dir, fileList = []) {
  const files = fs.readdirSync(dir);
  for (const file of files) {
    const fullPath = path.join(dir, file);
    if (fs.statSync(fullPath).isDirectory()) {
      findCsFiles(fullPath, fileList);
    } else if (fullPath.endsWith('.cs')) {
      fileList.push(fullPath);
    }
  }
  return fileList;
}

function extractEnums(filePath) {
  const content = fs.readFileSync(filePath, 'utf-8');
  const enums = [];
  
  // Match public enum EnumName { ... }
  const enumRegex = /public\s+enum\s+(\w+)\s*\{([^}]+)\}/g;
  let match;
  
  while ((match = enumRegex.exec(content)) !== null) {
    const enumName = match[1];
    const enumBody = match[2];
    
    // Extract values, ignoring comments and assignments
    const values = enumBody
      .split(',')
      .map(line => line.split('//')[0]) // remove inline comments
      .map(line => line.split('=')[0])  // remove assignments
      .map(line => line.trim())
      .filter(line => line.length > 0);
      
    enums.push({ name: enumName, values });
  }
  
  return enums;
}

function generateTsCode(allEnums) {
  let tsCode = `// ─── AUTO-GENERATED BY scripts/generate-enums.js ───\n`;
  tsCode += `// Do not edit this file directly. Update the C# enums instead.\n\n`;
  
  for (const { name, values } of allEnums) {
    const arrayName = `${name}Options`;
    const stringValues = values.map(v => `'${v}'`).join(', ');
    
    tsCode += `export const ${arrayName} = [${stringValues}] as const;\n`;
    tsCode += `export type ${name} = typeof ${arrayName}[number];\n\n`;
  }
  
  return tsCode;
}

function main() {
  const csFiles = findCsFiles(ENUMS_DIR);
  let allEnums = [];
  
  for (const file of csFiles) {
    const enumsInFile = extractEnums(file);
    allEnums = allEnums.concat(enumsInFile);
  }
  
  const tsCode = generateTsCode(allEnums);
  fs.writeFileSync(OUTPUT_FILE, tsCode, 'utf-8');
  console.log(`Successfully generated ${allEnums.length} enums to ${OUTPUT_FILE}`);
}

main();
